package com.veteranscout.cmsweb.util;

public class EmailBody {
    public String GetCmsAuthCodeHtml(){
        String strBody = "";
        // [##AUTH_CODE##]
        // [##SUBMIT_URL##]
        // [##YEAR##]

        strBody += "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">";
        strBody += "<html>";
        strBody += "<head>";
        strBody += "<meta http-equiv=\"content-language\" content=\"ko\">";
        strBody += "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">";
        strBody += "<meta name=\"description\" content=\"베테랑은 건설분야 직업소개소와 인력들을 쉽고 빠르게 연결하여 모두가 안심하고 편리하게 이용할 수 있는 중계 서비스를 제공합니다. \" />";
        strBody += "<meta name=\"keywords\"  content=\"Platformers,Platform,플랫포머스,베테랑,스카우트,건설,인력,일용직,구인구직\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Cache-Control\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Pragma\" />";
        strBody += "<title>문의 및 요청</title>";
        strBody += "</head>";
        strBody += "<BODY leftmargin=\"0\" bgcolor=\"#f5f5f5\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">";
        strBody += "<table width=\"100%\" border=\"0\" bgcolor=\"#f5f5f5\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" border=\"0\" bgcolor=\"#ffffff\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\"  bgcolor=\"#7bb0d1\" height=\"270\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "<td colspan=\"2\" height=\"43\"></td>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td colspan=\"2\"><a href=\"http://www.veteranscout.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr height=\"182\">";
        strBody += "<td style=\"vertical-align:text-top;color:#ffffff;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;font-size:16px;line-height:24px;letter-spacing:-1px;\">";
        strBody += "<p style=\"font-size:36px;letter-spacing:-4px;margin:26px 0;line-height:1;\">CMS 로그인 인증코드</p>";
        strBody += "안녕하세요.<br /> ";
        strBody += "인증번호 입력란에 입력해주세요.";
        strBody += "</td>";
        strBody += "<td align=\"right\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_img01.png\" alt=\"\" /></td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"700\"  bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:20px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-2px;line-height:1;\">인증번호</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"20\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"700\">";
        strBody += "<tr>";
        strBody += "<td height=\"2\" colspan=\"2\" bgcolor=\"#7bb0d1\"></td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td width=\"150\"  bgcolor=\"#f9f9f9\" style=\"color:#666666;font-weight:bold;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-1px;line-height:1;\">인증번호</td>";
        strBody += "<td style=\"color:#666666;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;line-height:1;\">[##AUTH_CODE##]</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td height=\"1\" colspan=\"2\" bgcolor=\"#e6e6e6\"></td>";
        strBody += "</tr>";									
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"15\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">* 본 메일은 발신전용이므로 회신하실 경우 답변되지 않습니다. 추가문의 사항은 대표전화 또는 온라인 문의를 통해 접수하여주시면<br /> &nbsp;  빠른 회신 드리도록 하겠습니다. </td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"40\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td align=\"center\" colspan=\"2\"><a href=\"[##SUBMIT_URL##]\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_btn.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" bgcolor=\"#e5e5e5\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td width=\"80\"></td>";
        strBody += "<td width=\"220\" align=\"left\"><a href=\"http://www.platformers.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo02.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">";
        strBody += "서울시 강남구 언주로 431 삼봉빌딩 8층<br />";
        strBody += "대표 : 박준석 ｜ 사업자등록번호 : 636-86-00384<br />";
        strBody += "대표 문의 : Tel. 02-3482-3366 ｜ Fax. 02-555-6221｜ E-mail. <a href=\"mailto:cs@platformers.co.kr\" style=\"color:#a6a6a6;\">cs@platformers.co.kr</a><br />";
        strBody += "Copyright ⓒ [##YEAR##] Platformers All Right Reserved.";
        strBody += "</td>";
        strBody += "<td width=\"80\"></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</body>";
        strBody += "</html>";
        return strBody;
    }

    public String GetCmsImsiPwdAuthCodeHtml(){
        String strBody = "";
        // [##AUTH_CODE##]
        // [##SUBMIT_URL##]
        // [##YEAR##]

        strBody += "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">";
        strBody += "<html>";
        strBody += "<head>";
        strBody += "<meta http-equiv=\"content-language\" content=\"ko\">";
        strBody += "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">";
        strBody += "<meta name=\"description\" content=\"베테랑은 건설분야 직업소개소와 인력들을 쉽고 빠르게 연결하여 모두가 안심하고 편리하게 이용할 수 있는 중계 서비스를 제공합니다. \" />";
        strBody += "<meta name=\"keywords\"  content=\"Platformers,Platform,플랫포머스,베테랑,스카우트,건설,인력,일용직,구인구직\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Cache-Control\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Pragma\" />";
        strBody += "<title>문의 및 요청</title>";
        strBody += "</head>";
        strBody += "<BODY leftmargin=\"0\" bgcolor=\"#f5f5f5\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">";
        strBody += "<table width=\"100%\" border=\"0\" bgcolor=\"#f5f5f5\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" border=\"0\" bgcolor=\"#ffffff\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\"  bgcolor=\"#7bb0d1\" height=\"270\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "<td colspan=\"2\" height=\"43\"></td>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td colspan=\"2\"><a href=\"http://www.veteranscout.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr height=\"182\">";
        strBody += "<td style=\"vertical-align:text-top;color:#ffffff;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;font-size:16px;line-height:24px;letter-spacing:-1px;\">";
        strBody += "<p style=\"font-size:36px;letter-spacing:-4px;margin:26px 0;line-height:1;\">CMS 비밀번호 재발급 인증코드</p>";
        strBody += "안녕하세요.<br /> ";
        strBody += "인증번호 입력란에 입력해주세요.";
        strBody += "</td>";
        strBody += "<td align=\"right\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_img01.png\" alt=\"\" /></td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"700\"  bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:20px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-2px;line-height:1;\">인증번호</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"20\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"700\">";
        strBody += "<tr>";
        strBody += "<td height=\"2\" colspan=\"2\" bgcolor=\"#7bb0d1\"></td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td width=\"150\"  bgcolor=\"#f9f9f9\" style=\"color:#666666;font-weight:bold;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-1px;line-height:1;\">인증번호</td>";
        strBody += "<td style=\"color:#666666;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;line-height:1;\">[##AUTH_CODE##]</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td height=\"1\" colspan=\"2\" bgcolor=\"#e6e6e6\"></td>";
        strBody += "</tr>";									
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"15\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">* 본 메일은 발신전용이므로 회신하실 경우 답변되지 않습니다. 추가문의 사항은 대표전화 또는 온라인 문의를 통해 접수하여주시면<br /> &nbsp;  빠른 회신 드리도록 하겠습니다. </td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"40\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td align=\"center\" colspan=\"2\"><a href=\"[##SUBMIT_URL##]\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_btn.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" bgcolor=\"#e5e5e5\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td width=\"80\"></td>";
        strBody += "<td width=\"220\" align=\"left\"><a href=\"http://www.platformers.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo02.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">";
        strBody += "서울시 강남구 언주로 431 삼봉빌딩 8층<br />";
        strBody += "대표 : 박준석 ｜ 사업자등록번호 : 636-86-00384<br />";
        strBody += "대표 문의 : Tel. 02-3482-3366 ｜ Fax. 02-555-6221｜ E-mail. <a href=\"mailto:cs@platformers.co.kr\" style=\"color:#a6a6a6;\">cs@platformers.co.kr</a><br />";
        strBody += "Copyright ⓒ [##YEAR##] Platformers All Right Reserved.";
        strBody += "</td>";
        strBody += "<td width=\"80\"></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</body>";
        strBody += "</html>";
        return strBody;
    }

    public String GetCmsImsiPwdHtml(){
        String strBody = "";
        // [##USER_NAME##]
        // [##USER_ID##]
        // [##USER_PWD##]
        // [##SUBMIT_URL##]
        // [##YEAR##]

        strBody += "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">";
        strBody += "<html>";
        strBody += "<head>";
        strBody += "<meta http-equiv=\"content-language\" content=\"ko\">";
        strBody += "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">";
        strBody += "<meta name=\"description\" content=\"베테랑은 건설분야 직업소개소와 인력들을 쉽고 빠르게 연결하여 모두가 안심하고 편리하게 이용할 수 있는 중계 서비스를 제공합니다. \" />";
        strBody += "<meta name=\"keywords\"  content=\"Platformers,Platform,플랫포머스,베테랑,스카우트,건설,인력,일용직,구인구직\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Cache-Control\" />";
        strBody += "<meta content=\"no-cache\" http-equiv=\"Pragma\" />";
        strBody += "<title>문의 및 요청</title>";
        strBody += "</head>";
        strBody += "<BODY leftmargin=\"0\" bgcolor=\"#f5f5f5\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">";
        strBody += "<table width=\"100%\" border=\"0\" bgcolor=\"#f5f5f5\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" border=\"0\" bgcolor=\"#ffffff\"  cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\"  bgcolor=\"#7bb0d1\" height=\"270\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "<td colspan=\"2\" height=\"43\"></td>";
        strBody += "<td width=\"50\" rowspan=\"3\"></td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td colspan=\"2\"><a href=\"http://www.veteranscout.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr height=\"182\">";
        strBody += "<td style=\"vertical-align:text-top;color:#ffffff;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;font-size:16px;line-height:24px;letter-spacing:-1px;\">";
        strBody += "<p style=\"font-size:36px;letter-spacing:-4px;margin:26px 0;line-height:1;\">CMS 비밀번호 재발급</p>";
        strBody += "안녕하세요.<br /> ";
        strBody += "[##USER_NAME##] 회원님 비밀번호 재발급이 완료되었습니다.<br/>";
        strBody += "아래 베테랑 바로가기를 클릭하여, 로그인 후 사용이 가능합니다.<br/>";
        strBody += "</td>";
        strBody += "<td align=\"right\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_img01.png\" alt=\"\" /></td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"700\"  bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:20px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-2px;line-height:1;\">인증번호</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"20\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"700\">";
        strBody += "<tr>";
        strBody += "<td height=\"2\" colspan=\"2\" bgcolor=\"#7bb0d1\"></td>";
        strBody += "</tr>";        
        strBody += "<td width=\"150\"  bgcolor=\"#f9f9f9\" style=\"color:#666666;font-weight:bold;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-1px;line-height:1;\">아이디</td>";
        strBody += "<td style=\"color:#666666;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;line-height:1;\">[##USER_ID##]</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td height=\"1\" colspan=\"2\" bgcolor=\"#e6e6e6\"></td>";
        strBody += "<tr>";
        strBody += "<td width=\"150\"  bgcolor=\"#f9f9f9\" style=\"color:#666666;font-weight:bold;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;letter-spacing:-1px;line-height:1;\">비밀번호</td>";
        strBody += "<td style=\"color:#666666;padding:15px;font-size:14px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;line-height:1;\">[##USER_PWD##]</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td height=\"1\" colspan=\"2\" bgcolor=\"#e6e6e6\"></td>";
        strBody += "</tr>";									
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"15\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">* 본 메일은 발신전용이므로 회신하실 경우 답변되지 않습니다. 추가문의 사항은 대표전화 또는 온라인 문의를 통해 접수하여주시면<br /> &nbsp;  빠른 회신 드리도록 하겠습니다. </td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"40\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td align=\"center\" colspan=\"2\"><a href=\"[##SUBMIT_URL##]\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_btn.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"50\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "<tr>";
        strBody += "<td>";
        strBody += "<table width=\"800\" bgcolor=\"#e5e5e5\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "<tr>";
        strBody += "<td width=\"80\"></td>";
        strBody += "<td width=\"220\" align=\"left\"><a href=\"http://www.platformers.co.kr\" target=\"_blank\"><img src=\"http://www.veteranscout.co.kr/html/images/mailing_logo02.png\" alt=\"\"  border=\"0\" /></a></td>";
        strBody += "<td style=\"font-size:13px;font-family:맑은 고딕, Malgun Gothic,굴림, Gulim, sans-serif;color:#a6a6a6;letter-spacing:-1px;line-height:1.6;\">";
        strBody += "서울시 강남구 언주로 431 삼봉빌딩 8층<br />";
        strBody += "대표 : 박준석 ｜ 사업자등록번호 : 636-86-00384<br />";
        strBody += "대표 문의 : Tel. 02-3482-3366 ｜ Fax. 02-555-6221｜ E-mail. <a href=\"mailto:cs@platformers.co.kr\" style=\"color:#a6a6a6;\">cs@platformers.co.kr</a><br />";
        strBody += "Copyright ⓒ [##YEAR##] Platformers All Right Reserved.";
        strBody += "</td>";
        strBody += "<td width=\"80\"></td>";
        strBody += "</tr>";
        strBody += "<tr><td height=\"30\" colspan=\"4\"></td></tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</td>";
        strBody += "</tr>";
        strBody += "</table>";
        strBody += "</body>";
        strBody += "</html>";
        return strBody;
    }
}
